[project]
name="naturewatch_camera_server"
dynamic=["version"]
dependencies = [
   "flask",
   "opencv-python",
   "numpy",
   "imutils == 0.5.4",
   "RPi.GPIO",
]
readme="README.md"
license="GPL-3.0"
license-files=["LICENSE"]

[project.scripts]
naturewatch_camera_server = "naturewatch_camera_server:__main__"

[tool.setuptools.packages.find]
include=["naturewatch_camera_server"]

[project.optional-dependencies]
dev = [
    "black",
    "pytest"
]

[tool.black]
line-length = 79
include = '.pyi?$'
exclude = '''
/(
    .git
    | .hg
    | .mypy_cache
    | .tox
    | .venv
    | _build
    | buck-out
    | build
    | dist
)/
'''

[tool.pytest]
minversion = "9.0"
addopts = ["-ra", "-q"]
testpaths = [
    "tests",
]
